const wordList = [
  { word: "Book", hint: "Contains stories and information." },
  { word: "Dog", hint: "A loyal pet with four legs." },
  { word: "Cake", hint: "A sweet dessert often served on birthdays." },
  { word: "Sun", hint: "A bright star that provides light and heat." },
  { word: "Tree", hint: "A tall plant with a trunk and branches." },
  { word: "Car", hint: "A vehicle used for transportation." },
  { word: "Cat", hint: "A furry animal often kept as a pet." },
  { word: "Ball", hint: "A round object used in various sports and games." },
  { word: "Rain", hint: "Water falling from the sky." },
  { word: "Bird", hint: "A flying animal with feathers." },
  { word: "House", hint: "A building where people live." },
  { word: "Moon", hint: "A natural satellite that orbits the Earth." },
  { word: "Bed", hint: "A piece of furniture used for sleeping." },
  { word: "Key", hint: "A small metal object used to unlock things." },
  { word: "Fish", hint: "An aquatic animal with gills and fins." },
  { word: "Book", hint: "Contains stories and information." },
  { word: "Dog", hint: "A loyal pet with four legs." },
  { word: "Cake", hint: "A sweet dessert often served on birthdays." },
  { word: "Sun", hint: "A bright star that provides light and heat." },
  { word: "Tree", hint: "A tall plant with a trunk and branches." },
  { word: "Car", hint: "A vehicle used for transportation." },
  { word: "Cat", hint: "A furry animal often kept as a pet." },
  { word: "Ball", hint: "A round object used in various sports and games." },
  { word: "Rain", hint: "Water falling from the sky." },
  { word: "Bird", hint: "A flying animal with feathers." },
  { word: "House", hint: "A building where people live." },
  { word: "Moon", hint: "A natural satellite that orbits the Earth." },
  { word: "Bed", hint: "A piece of furniture used for sleeping." },
  { word: "Key", hint: "A small metal object used to unlock things." },
  { word: "Fish", hint: "An aquatic animal with gills and fins." }
];

