const wordList = [
  { word: "Console", hint: "A gaming device connected to a TV or monitor." },
  { word: "Controller", hint: "A handheld device used to interact with video games." },
  { word: "Keyboard", hint: "A set of keys used to input data into a computer or gaming system." },
  { word: "Mouse", hint: "A pointing device used to control the cursor on a computer screen." },
  { word: "GPU", hint: "A specialized electronic circuit designed to rapidly manipulate and alter memory to accelerate the creation of images in a frame buffer." },
  { word: "CPU", hint: "The primary component of a computer responsible for executing instructions." },
  { word: "RAM", hint: "A type of computer memory that can be accessed randomly, used to store data temporarily." },
  { word: "VR", hint: "A simulated experience that can be similar to or completely different from the real world." },
  { word: "AR", hint: "An enhanced version of reality created by the use of technology to overlay digital information on an image of something being viewed through a device." },
  { word: "LAN", hint: "A computer network that connects devices in a limited geographical area." },
  { word: "Router", hint: "A device that forwards data packets between computer networks." },
  { word: "Server", hint: "A computer or system that provides resources, data, or services to other computers, known as clients, over a network." },
  { word: "Modem", hint: "A device or program that enables a computer to transmit data over telephone or cable lines." },
  { word: "Firmware", hint: "Permanent software programmed into a read-only memory." },
  { word: "Pixel", hint: "The smallest controllable element of a picture represented on the screen." },
  { word: "Resolution", hint: "The number of pixels in each dimension that can be displayed on a screen." },
  { word: "Frame Rate", hint: "The frequency at which consecutive images, or frames, appear on a display." },
  { word: "Latency", hint: "The time it takes for data to travel from one point to another in a network." },
  { word: "Download", hint: "The process of receiving data from a remote system." },
  { word: "Upload", hint: "The process of sending data from a local system to a remote system." }
];
